# Generated by Django 5.0 on 2023-12-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_alter_log_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
