# Generated by Django 5.0 on 2023-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_delete_usermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendarID',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
