# Generated by Django 5.0 on 2023-12-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0006_alter_log_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userloginhistory',
            name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='surname',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendarID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='street',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phonenumber',
            field=models.CharField(default=123456789, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.event')),
                ('userdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.userdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='PhoneNumbers',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
