# Generated by Django 5.0 on 2023-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0007_remove_usercontact_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
